{% set name = "execnet" %}
{% set version = "2.0.0" %}
{% set hash = "c98d4317b0c8ddcfea75523d6ace65c694b606d00d74e7a22e5209093bb94798" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python 2.7|>=3.5
    - setuptools
    - setuptools_scm
  run:
    - python 2.7|>=3.5

test:
  imports:
    - execnet

about:
  home: http://codespeak.net/execnet
  dev_url: https://github.com/pytest-dev/execnet
  doc_url: http://codespeak.net/execnet
  license: MIT
  license_file: LICENSE
  summary: distributed Python deployment and communication

extra:
  recipe-maintainers:
    - nicoddemus
