{% set name = "execnet" %}
{% set version = "2.1.1" %}
{% set hash = "5189b52c6121c24feae288166ab41b32549c7e2348652736540b9e6e7d4e72e3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - execnet

about:
  home: http://codespeak.net/execnet
  dev_url: https://github.com/pytest-dev/execnet
  doc_url: http://codespeak.net/execnet
  license: MIT
  license_file: LICENSE
  summary: distributed Python deployment and communication

extra:
  recipe-maintainers:
    - nicoddemus
