{% set name = "execnet" %}
{% set version = "2.0.2" %}
{% set hash = "cc59bc4423742fd71ad227122eb0dd44db51efb3dc4095b45ac9a08c770096af" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling
    - hatch-vcs
  run:
    - python >=3.7

test:
  imports:
    - execnet

about:
  home: http://codespeak.net/execnet
  dev_url: https://github.com/pytest-dev/execnet
  doc_url: http://codespeak.net/execnet
  license: MIT
  license_file: LICENSE
  summary: distributed Python deployment and communication

extra:
  recipe-maintainers:
    - nicoddemus
